### ISSUE TITLE
"imodeljs/desktop-starter" failed to initialize electron IPC

### ISSUE THREAD

**Issue by namsancow** [imodeljs/imodeljs#113] opened 2020-09-19 01:16 UTC
Yesterday, "imodeljs/desktop-starter" was updated as 2.6.0.
And I tested the new version ""imodeljs/desktop-starter" on Win 10 64bit & Chrome.

The process of "npm install" is ok!
The process of "npm build" is also ok!
However, after messaging of "compiled successfully", there is an unseen warning in the previous version as following:

![image](https://user-images.githubusercontent.com/22971147/93655936-a2e66000-fa61-11ea-9de9-29c5798ccd99.png)

And after loading "desktop-starter" on electron, there is also an unseen warning in the previous version as following:

![image](https://user-images.githubusercontent.com/22971147/93656126-0b820c80-fa63-11ea-8958-f861f496f9a3.png)
![image](https://user-images.githubusercontent.com/22971147/93656145-25235400-fa63-11ea-8127-44bfcb558d1b.png)
![image](https://user-images.githubusercontent.com/22971147/93656159-38362400-fa63-11ea-9f54-0d5fd635c806.png)

And the default model is not displayed. This issue is not seen in previous versions.
If I don't understand it well, please let me know.

**Comment by calebmshafer** [comment] 2020-09-19 18:59
duplicate of https://github.com/imodeljs/desktop-starter/issues/32. closing.

**Closed by calebmshafer** 2020-09-19 18:59 UTC
