### ISSUE TITLE
Getting Log in Error

### ISSUE THREAD

**Issue by fella752** [imodeljs/imodeljs#73] opened 2020-02-25 10:25 UTC
Error 400
unauthorized_client
Invalid grant type for client

For more information please refer to SEQ logs using this query:
@Timestamp < DateTime('2020-02-25T10:24:27.625103Z') and RequestId='0HLTPD7HR2FME:00000165'
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Opening-an-iModel-via-the-IModelDb-class---iModel.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.imodeljs.org/learning/backend/imodeldb/

**Comment by williamkbentley** [comment] 2020-02-25 14:40
This looks like a duplicate of #70. See that issue for details and debugging suggestions.

**Closed** 2020-02-25 14:46 UTC
