### ISSUE TITLE
I couldn't open the local ibim file using simple-viewer-app.

### ISSUE THREAD

**Issue by shenshengyi** [imodeljs/imodeljs#53] opened 2019-11-29 00:34 UTC
I couldn't open the local ibim file using simple-viewer-app.
Always prompt Invalid iModelToken for RPC operation request，Can you help me.thanks.

* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Community-Resources---iModel.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://imodeljs.github.io/iModelJs-docs-output/learning/communityresources/

**Comment by calebmshafer** [comment] 2019-12-02 13:19
Duplicate of #52. Closing this to continue the conversation there.

**Closed by calebmshafer** 2019-12-02 13:19 UTC
