### ISSUE TITLE
Attempt to upload an app to heroku

### ISSUE THREAD

**Issue by LastLow098** [imodeljs/imodeljs#1404] opened 2021-05-16 00:15 UTC
Hello,
I am trying to upload this app to heroku, but the app crashes with the H10 error - 
2021-05-16T00:09:43.239969+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=glacial-river-93766.herokuapp.com request_id=d8579576-b201-4726-b8ac-9208f0d7cba7 fwd="93.81.221.158" dyno= connect= service= status=503 bytes= protocol=https
2021-05-16T00:09:43.900179+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=glacial-river-93766.herokuapp.com request_id=51a2c4b4-10a4-4375-b42b-7a26c90d8762 fwd="93.81.221.158" dyno= connect= service= status=503 bytes= protocol=https

And I can't figure out how to solve this problem
Can you help me with this issue
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Developing-a-web-viewer---iTwin.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.itwinjs.org/learning/tutorials/develop-web-viewer/

**Comment by Carl-Hinkle** [comment] 2021-05-17 17:10
Hi,

It's hard to provide too much assistance without more information about what you're trying to do.  

From a quick look at Heroku's documentation, it looks like you'll need to do a little work to deploy a static web site.  This guide might be helpful: https://www.geeksforgeeks.org/how-to-deploy-a-basic-static-html-website-to-heroku/. 

If you have the option, I suggest using https://www.netlify.com/ instead of heroku for hosting.

**Comment by LastLow098** [comment] 2021-06-01 15:45
Perhaps you have an algorithm for deploying this application on a hosting service?
What needs to be changed and where, regardless of which hosting will be used?
My task is to be able to access this application from the browser.

**Comment by calebmshafer** [comment] 2021-06-09 13:08
@LastLow098 we use, and suggest, [create-react-app](https://create-react-app.dev/) as the way to build the an iTwin.js web application and they provide details on how to deploy a Heroku application, https://create-react-app.dev/docs/deployment#heroku.

If you run into any issues with deploying your viewer using their suggestions please let us know. Thanks

**Comment by LastLow098** [comment] 2021-06-11 05:23
Hello,
I looked through the site that you recommended to me, but did not find a solution to my problem
I deployed the application on heroku, and also recorded the deployment so that the error can be seen, and how it occurs
At the launch and build stage, the app crashes.

https://still-garden-83058.herokuapp.com/ - link to the app
https://disk.yandex.ru/d/cPoz3qwJSKHOew - link to the video that shows the app download and also logs

**Comment by Carl-Hinkle** [comment] 2021-06-22 16:39
In addition to the points in the last post about setting up your config variables, make sure that you have the correct buildpack configured in your Heroku app as described here: https://www.geeksforgeeks.org/how-to-deploy-react-app-to-heroku/ 

I confirmed that this does work and I was able to deploy an iTwin app on Heroku.

**Comment by Carl-Hinkle** [comment] 2021-06-25 14:54
@LastLow098 I'm going to close this issue since the steps above should solve the problem.  Please feel free to reopen or start a new Issue if you need more help.  Thanks!

**Closed by Carl-Hinkle** 2021-06-25 14:54 UTC

**Comment by Carl-Hinkle** [comment] 2021-07-26 16:58
We've just published a [guide](https://medium.com/itwinjs/deploying-the-itwin-viewer-to-a-web-host-d45c5cfdf0cf) that explains how to deploy to Heroku and Netlify.  If you're still having trouble, please check it out.
