### ISSUE TITLE
http://www.bentley.com/schemas/Bentley.ECXML.3.1 link is broken

### ISSUE THREAD

**Issue by Nazeer-Hussain** [imodeljs/imodeljs#876] opened 2021-03-02 15:16 UTC
The ECXML3 link as given on the page
https://github.com/imodeljs/imodeljs/blob/master/docs/bis/intro/bis-schema-validation.md
is broken and results in 404 not found error

the link in question is: 
http://www.bentley.com/schemas/Bentley.ECXML.3.1

**Comment by ColinKerr** [comment] 2021-03-05 00:52
Hi Nazeer, 
  Thanks for reporting this.  The xmlns url for ECSchemas are not valid links.  We do have plans to publish our xsds along with our BIS Schemas as open source soon.

Based on your feedback I have created this PR to clean up the docs to reduce confusion and make one other minor improvement.

Check it out here: https://github.com/imodeljs/imodeljs/pull/906

Thanks again for filing the issue and please do file more if you see other issues with our docs.  You can even file an issue from the bottom of any page on our doc site:
![image](https://user-images.githubusercontent.com/33028649/110051002-11269280-7d23-11eb-8889-b790264623d6.png)

I'm closing this issue because the PR to fix the issue is in progress.

 - Colin

**Closed by ColinKerr** 2021-03-05 00:52 UTC
